[tools]
ast-grep = "latest"
bun = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
lua-language-server = "latest"
node = "lts"
"npm:eslint" = "latest"
"npm:prettier" = "latest"
"npm:stylelint-lsp" = "latest"
pnpm = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
